In [3]:
#Simple quick sort
def quicksort(arr):
    if len(arr) <= 1:
        return(arr)
    pivot = arr[len(arr)/2]
    left = [x for x in arr if x< pivot]
    right = [x for x in arr if x> pivot]
    middle = [x for x in arr if x == pivot]
    return quicksort(left) + middle + quicksort(right)

In [4]:
#Basic data types
x = 3
print(type(x))
print(x+1)
print(x-1)
print(x*2)
print(x**2)
x+=1
print(x)
x*=2
print(x)

<class 'int'>
4
2
6
9
4
8


In [6]:
#Loops
animals = ["cat","dog","mouse"]
for i in animals:
    print(i)

cat
dog
mouse


In [8]:
for idx, animal in enumerate(animals):
    print("%d: %s" %(idx, animal))

0: cat
1: dog
2: mouse


In [10]:
nums = range(0,4)
square = []
for x in nums:
    square.append(x**2)
square

[0, 1, 4, 9]

In [12]:
[x**2 for x in nums]

[0, 1, 4, 9]

In [13]:
nums = range(0,15)
[x**2 for x in nums if x%2 == 0] #only even numbers square

[0, 4, 16, 36, 64, 100, 144, 196]

In [15]:
#Dictionaries:
d = {'cat':'cute',"dog":"furry"}
print(d['cat'])

cute


In [17]:
print('cat' in d)

True


In [18]:
d['fish'] = 'wet'

In [22]:
d.get('fish')

'wet'

In [23]:
d.get("boat")

In [25]:
d.get("boat","na")

'na'

In [27]:
d = {'person': 2, "cat":34,"spider": 8}
for animal in d:
    print(d[animal])

2
8
34


In [32]:
d = {'person': 2, "cat":34,"spider": 8}
for legs, animal in enumerate(d):
    print("%s has %d legs"%(animal,legs))

person has 0 legs
spider has 1 legs
cat has 2 legs


In [35]:
nums = range(0,15)
even_num_square = {x:x**2 for x in nums if x%2 == 0}
even_num_square

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196}

In [42]:
d = {(x,x+1): x for x in range(10)}
print(type(d))
d

<class 'dict'>


{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [51]:
print(d[(3,4)])
print(d[(9,10)])

print(d[(1,2)])

3
9
1


In [55]:
#Numpy
import numpy as np
d = np.full((2,2),7)
d

C:\Program Files\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 7.,  7.],
       [ 7.,  7.]])

In [58]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a[:2,1:3]
b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[2, 3],
       [6, 7]])

In [70]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1 = a[1,:]
print(row_r1)
print(row_r1.shape)

row_r1 = a[1:2,]
print(row_r1)
print(row_r1.shape)

[5 6 7 8]
(4,)
[[5 6 7 8]]
(1, 4)


In [73]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1)
print(col_r2)
print(col_r1.shape)
print(col_r2.shape)

[ 2  6 10]
[[ 2]
 [ 6]
 [10]]
(3,)
(3, 1)


In [79]:
#Integer array indeing
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[[0,1,2],[0,1,0]]) #Print (0,0), (1,1) and (2,0) elements
print(a[0,0], a[1,1], a[2,0])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
1 4 5


In [83]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

#array of indices 
b = np.array([0,2,0,1])
print(a[np.arange(4),b])
print("\n")
print(a[0,0],a[1,2],a[2,0],a[3,1])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


1 6 7 11


In [86]:
#Boolean array indexing
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
