In [4]:
import numpy as np

In [7]:
train = np.array([[1,2,3,4],[5,6,7,8],[1,2,1,4]])
test = np.array([[0,1,2,1],[1,2,3,1]])

In [41]:
train_rsh = np.reshape(train.transpose(), (1,4,3))
test_rsh = np.reshape(test,(2,4,1))

In [151]:
train = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2]])
test = np.array([[6,6,6,6],[9,9,9,9]])
dist3 = np.empty([3,2])
train = np.reshape(train.transpose(), [1,4,3])
test = np.reshape(test,[2,4,1])
test - train
#np.sum((test_rsh - train_rsh)**2, axis = 1)

array([[[6, 5, 4],
        [6, 5, 4],
        [6, 5, 4],
        [6, 5, 4]],

       [[9, 8, 7],
        [9, 8, 7],
        [9, 8, 7],
        [9, 8, 7]]])

In [147]:
train = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2]])
test = np.array([[6,6,6,6],[9,9,9,9]])
ab = np.reshape(train.transpose(),(1,4,3))
ab[0,3,:]



array([0, 1, 2])

In [93]:
tempu = (test-train)
tempu[0,:,0]

array([4, 4, 3, 2])

In [83]:
train = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
temptr = np.reshape(train, (1,4,3))

In [84]:
temptr[0,0,:]

array([1, 1, 1])

In [88]:
test = np.array([[5,5,5,5],[0,0,0,0]])
tempte = np.reshape(test, [2,4,1])
tempte[0,:,0]

array([5, 5, 5, 5])

In [24]:
dist2 = np.empty([3,2])
for i in np.arange(2):
    dist2[:,i] = np.sum((train-test[i])**2, axis = 1)
dist2

array([[  12.,    9.],
       [ 124.,   97.],
       [  12.,   13.]])

In [26]:
x = np.array([1,4,3,2])
x[np.argsort(x)]

array([1, 2, 3, 4])

In [17]:
dist = np.empty([3,2])
for i in np.arange(3):
    for j in np.arange(2):
        dist[i,j] = np.sum((train[i,:] - test[j,:])**2)
dist

array([[  12.,    9.],
       [ 124.,   97.],
       [  12.,   13.]])

In [21]:
np.sum((np.array([1,2,3,4])-np.array([-1,0]))**2)

9

In [39]:
lst = np.array([0,2,2,3])
(np.bincount(lst))

array([1, 0, 2, 1], dtype=int64)